{
  "resourceType": "GMRoom",
  "resourceVersion": "1.0",
  "name": "rMinigame4vs_Magic",
  "creationCodeFile": "",
  "inheritCode": false,
  "inheritCreationOrder": false,
  "inheritLayers": false,
  "instanceCreationOrder": [
    {"name":"inst_4CFF078","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_618054A0","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_6B169226","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_7AAEE47","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5E60999F","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_668F666E","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_4A4FD9B7","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_7B91A1E3","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_66C028C0","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_49B5D3DE","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_4F4E60CE","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3CB17E90","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_740FEB0A","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_1094B303","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5DE7FF3A","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3CBB2A02","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5BD3DC8B","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_751C1453","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3783AF4A","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_102901CB","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_231CF1CB","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_1CA4D152","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_513AE625","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_19DA12C4","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_45093277","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_4214E33F","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5320AC","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_29CF1C","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_221D8E29","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_6289B632","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_721FF4B4","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_1128A60B","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_778C2AE1","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_4EA9A51C","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_22125F6","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5B906AE0","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_2C3A00F9","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3CF8DC18","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_340F5059","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5BBAB330","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_A49F449","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_4C324638","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_26B31716","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_4457CBAE","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3ADB6D7D","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_58F9A7A8","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_1F8B9096","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_7801DA5E","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_1309DBD8","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_7CD806E7","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_1A30EAA2","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_172344E1","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_181C1B5C","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3A3CD72B","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_20C6CC7","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_F9F76D8","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_6CB95148","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_6D1A293B","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_23C80A41","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5D951C8F","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_183D5A5D","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_6EF8CF11","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_5A66277D","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_33D866CB","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_38D6ADBE","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_3B48766A","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_61A1D45C","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_31BDA9D4","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_54360962","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_34524663","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_29866BCE","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_7C7C9B60","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_458849EF","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_69B07997","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_7BF8D438","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_40A89088","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_293FF203","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
    {"name":"inst_2830AE50","path":"rooms/rMinigame4vs_Magic/rMinigame4vs_Magic.yy",},
  ],
  "isDnd": false,
  "layers": [
    {"resourceType":"GMRInstanceLayer","resourceVersion":"1.0","name":"Givers","depth":0,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"instances":[
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3B48766A","colour":4294901760,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"propertyId":{"name":"player_turn","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"value":"1",},
          ],"rotation":0.0,"scaleX":11.0,"scaleY":8.0,"x":32.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_61A1D45C","colour":4278190335,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"propertyId":{"name":"player_turn","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":11.0,"scaleY":8.0,"x":416.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_31BDA9D4","colour":4278255360,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"propertyId":{"name":"player_turn","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":11.0,"scaleY":8.0,"x":32.0,"y":320.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_54360962","colour":4278255615,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"propertyId":{"name":"player_turn","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"value":"4",},
          ],"rotation":0.0,"scaleX":11.0,"scaleY":8.0,"x":416.0,"y":320.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_69B07997","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_GiverID","path":"objects/objMinigame4vs_Magic_GiverID/objMinigame4vs_Magic_GiverID.yy",},"properties":[],"rotation":0.0,"scaleX":11.0,"scaleY":8.0,"x":1824.0,"y":160.0,},
      ],"layers":[],"properties":[],"userdefinedDepth":false,"visible":false,},
    {"resourceType":"GMRInstanceLayer","resourceVersion":"1.0","name":"Curtains","depth":100,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"instances":[
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_7BF8D438","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Curtain","path":"objects/objMinigame4vs_Magic_Curtain/objMinigame4vs_Magic_Curtain.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":32.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_40A89088","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Curtain","path":"objects/objMinigame4vs_Magic_Curtain/objMinigame4vs_Magic_Curtain.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":416.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_293FF203","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Curtain","path":"objects/objMinigame4vs_Magic_Curtain/objMinigame4vs_Magic_Curtain.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":32.0,"y":320.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_2830AE50","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Curtain","path":"objects/objMinigame4vs_Magic_Curtain/objMinigame4vs_Magic_Curtain.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":416.0,"y":320.0,},
      ],"layers":[],"properties":[],"userdefinedDepth":false,"visible":false,},
    {"resourceType":"GMRInstanceLayer","resourceVersion":"1.0","name":"Actors","depth":200,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"instances":[
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_34524663","colour":4294901760,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":192.0,"y":96.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_29866BCE","colour":4278190335,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"propertyId":{"name":"reference","path":"objects/objPlayerReference/objPlayerReference.yy",},"value":"1",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":576.0,"y":96.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_7C7C9B60","colour":4278255360,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"propertyId":{"name":"reference","path":"objects/objPlayerReference/objPlayerReference.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":192.0,"y":480.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_458849EF","colour":4278255615,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objPlayerReference","path":"objects/objPlayerReference/objPlayerReference.yy",},"propertyId":{"name":"reference","path":"objects/objPlayerReference/objPlayerReference.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":576.0,"y":480.0,},
      ],"layers":[],"properties":[],"userdefinedDepth":false,"visible":true,},
    {"resourceType":"GMRInstanceLayer","resourceVersion":"1.0","name":"Items","depth":300,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"instances":[
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3CB17E90","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":1872.0,"y":176.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_740FEB0A","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"1",},
          ],"rotation":0.5308178,"scaleX":1.0,"scaleY":1.0,"x":1936.0,"y":176.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_1094B303","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":2000.0,"y":176.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5DE7FF3A","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":2064.0,"y":176.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3CBB2A02","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"4",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":2128.0,"y":176.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5BD3DC8B","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"5",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":1872.0,"y":272.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_751C1453","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"6",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":1936.0,"y":272.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3783AF4A","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"7",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":2000.0,"y":272.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_102901CB","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"8",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":2064.0,"y":272.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_231CF1CB","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"9",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":2128.0,"y":272.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4214E33F","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":464.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5320AC","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"1",},
          ],"rotation":0.5308178,"scaleX":1.0,"scaleY":1.0,"x":528.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_29CF1C","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":592.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_221D8E29","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":656.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_6289B632","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"4",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":720.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_721FF4B4","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"5",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":464.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_1128A60B","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"6",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":528.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_778C2AE1","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"7",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":592.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4EA9A51C","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"8",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":656.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_22125F6","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"9",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":720.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5B906AE0","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":464.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_2C3A00F9","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"1",},
          ],"rotation":0.5308178,"scaleX":1.0,"scaleY":1.0,"x":528.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3CF8DC18","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":592.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_340F5059","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":656.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5BBAB330","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"4",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":720.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_A49F449","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"5",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":464.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4C324638","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"6",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":528.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_26B31716","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"7",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":592.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4457CBAE","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"8",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":656.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3ADB6D7D","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"9",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":720.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_58F9A7A8","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":80.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_1F8B9096","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"1",},
          ],"rotation":0.5308178,"scaleX":1.0,"scaleY":1.0,"x":144.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_7801DA5E","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":208.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_1309DBD8","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":272.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_7CD806E7","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"4",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":336.0,"y":48.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_1A30EAA2","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"5",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":80.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_172344E1","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"6",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":144.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_181C1B5C","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"7",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":208.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_3A3CD72B","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"8",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":272.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_20C6CC7","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"9",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":336.0,"y":144.14754,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_F9F76D8","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":80.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_6CB95148","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"1",},
          ],"rotation":0.5308178,"scaleX":1.0,"scaleY":1.0,"x":144.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_6D1A293B","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"2",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":208.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_23C80A41","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"3",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":272.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5D951C8F","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"4",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":336.0,"y":336.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_183D5A5D","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"5",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":80.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_6EF8CF11","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"6",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":144.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5A66277D","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"7",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":208.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_33D866CB","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"8",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":272.0,"y":432.14755,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_38D6ADBE","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"properties":[
            {"resourceType":"GMOverriddenProperty","resourceVersion":"1.0","name":"","objectId":{"name":"objMinigame4vs_Magic_Items","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"propertyId":{"name":"order","path":"objects/objMinigame4vs_Magic_Items/objMinigame4vs_Magic_Items.yy",},"value":"9",},
          ],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":336.0,"y":432.14755,},
      ],"layers":[],"properties":[],"userdefinedDepth":false,"visible":true,},
    {"resourceType":"GMRInstanceLayer","resourceVersion":"1.0","name":"Collisions","depth":400,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"instances":[
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4CFF078","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":25.0,"scaleY":1.0,"x":0.0,"y":0.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_618054A0","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":25.0,"scaleY":1.0,"x":0.0,"y":576.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_6B169226","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":25.0,"scaleY":1.0,"x":0.0,"y":288.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_7AAEE47","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":0.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_5E60999F","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":384.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_668F666E","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":768.0,"y":32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4A4FD9B7","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":768.0,"y":320.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_7B91A1E3","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":384.0,"y":320.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_66C028C0","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":0.0,"y":320.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_1CA4D152","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":13.0,"scaleY":1.0,"x":1792.0,"y":128.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_513AE625","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":13.0,"scaleY":1.0,"x":1792.0,"y":416.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_19DA12C4","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":1792.0,"y":160.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_45093277","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objBlock","path":"objects/objBlock/objBlock.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":8.0,"x":2176.0,"y":160.0,},
      ],"layers":[],"properties":[],"userdefinedDepth":false,"visible":false,},
    {"resourceType":"GMRInstanceLayer","resourceVersion":"1.0","name":"Managers","depth":500,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"instances":[
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_49B5D3DE","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Controller","path":"objects/objMinigame4vs_Magic_Controller/objMinigame4vs_Magic_Controller.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":-32.0,},
        {"resourceType":"GMRInstance","resourceVersion":"1.0","name":"inst_4F4E60CE","colour":4294967295,"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"objectId":{"name":"objMinigame4vs_Magic_Intro","path":"objects/objMinigame4vs_Magic_Intro/objMinigame4vs_Magic_Intro.yy",},"properties":[],"rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":32.0,"y":-32.0,},
      ],"layers":[],"properties":[],"userdefinedDepth":false,"visible":true,},
    {"resourceType":"GMRTileLayer","resourceVersion":"1.1","name":"Tiles","depth":600,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"layers":[],"properties":[],"tiles":{"SerialiseHeight":19,"SerialiseWidth":75,"TileCompressedData":[
-25,7,-50,-2147483648,25,7,-2147483648,126,-2147483648,126,-2147483648,126,-2147483648,126,-2147483648,126,-2147483648,7,0,126,0,126,-2147483648,126,0,126,0,126,-2147483648,7,-50,-2147483648,25,7,-2147483648,135,0,135,0,135,0,135,0,135,-2147483648,7,0,135,0,135,0,135,0,135,0,135,-2147483648,7,-50,-2147483648,2,7,-2147483648,-9,7,3,-2147483648,7,0,-9,7,2,-2147483648,7,-50,
-2147483648,25,7,-2147483648,126,0,126,0,126,0,126,0,126,-2147483648,7,0,126,0,126,0,126,0,126,0,126,-2147483648,7,-30,-2147483648,1,0,-13,7,-6,-2147483648,25,7,-2147483648,135,0,135,0,135,0,135,0,135,-2147483648,7,0,135,0,135,0,135,0,135,0,135,-2147483648,7,-30,-2147483648,14,0,7,-2147483648,126,0,126,0,126,0,126,0,
126,0,7,-6,-2147483648,2,7,-2147483648,-9,7,3,-2147483648,7,0,-9,7,2,-2147483648,7,-30,-2147483648,14,0,7,-2147483648,135,0,135,0,135,0,135,0,135,0,7,-6,-2147483648,2,7,-2147483648,-9,0,2,-2147483648,7,-10,0,2,-2147483648,7,-30,-2147483648,3,0,7,-2147483648,-9,7,2,0,7,-6,-2147483648,2,7,-2147483648,-9,0,2,-2147483648,7,-10,0,2,
-2147483648,7,-30,-2147483648,14,0,7,-2147483648,126,0,126,0,126,0,126,0,126,0,7,-6,-2147483648,-25,7,-30,-2147483648,14,0,7,-2147483648,135,0,135,0,135,0,135,0,135,0,7,-6,-2147483648,25,7,-2147483648,126,-2147483648,126,-2147483648,126,-2147483648,126,-2147483648,126,0,7,0,126,0,126,0,126,-2147483648,126,-2147483648,126,-2147483648,7,-30,-2147483648,3,0,7,-2147483648,-9,
7,2,0,7,-6,-2147483648,25,7,-2147483648,135,0,135,0,135,0,135,0,135,0,7,0,135,0,135,0,135,0,135,0,135,-2147483648,7,-30,-2147483648,3,0,7,-2147483648,-10,0,1,7,-6,-2147483648,2,7,-2147483648,-9,7,3,0,7,0,-9,7,2,-2147483648,7,-30,-2147483648,3,0,7,-2147483648,-10,0,1,7,-6,-2147483648,25,7,-2147483648,126,0,
126,0,126,0,126,0,126,0,7,0,126,0,126,0,126,0,126,0,126,-2147483648,7,-30,-2147483648,1,0,-13,7,-6,-2147483648,25,7,-2147483648,135,0,135,0,135,0,135,0,135,0,7,0,135,0,135,0,135,0,135,0,135,-2147483648,7,-50,-2147483648,2,7,-2147483648,-9,7,3,-2147483648,7,0,-9,7,2,-2147483648,7,-50,-2147483648,2,7,
-2147483648,-9,0,2,-2147483648,7,-10,0,2,-2147483648,7,-50,-2147483648,2,7,-2147483648,-10,0,1,7,-10,0,2,-2147483648,7,-50,-2147483648,-25,7,-50,-2147483648,],"TileDataFormat":1,},"tilesetId":{"name":"tlsMinigame4vs_Magic","path":"tilesets/tlsMinigame4vs_Magic/tlsMinigame4vs_Magic.yy",},"userdefinedDepth":false,"visible":true,"x":0,"y":0,},
    {"resourceType":"GMRBackgroundLayer","resourceVersion":"1.0","name":"Background","animationFPS":0.0,"animationSpeedType":0,"colour":4294967295,"depth":700,"effectEnabled":true,"effectType":null,"gridX":32,"gridY":32,"hierarchyFrozen":false,"hspeed":0.0,"htiled":true,"inheritLayerDepth":false,"inheritLayerSettings":false,"inheritSubLayers":true,"inheritVisibility":true,"layers":[],"properties":[],"spriteId":{"name":"sprBkgMinigame4vs_Magic","path":"sprites/sprBkgMinigame4vs_Magic/sprBkgMinigame4vs_Magic.yy",},"stretch":false,"userdefinedAnimFPS":false,"userdefinedDepth":false,"visible":true,"vspeed":0.0,"vtiled":true,"x":0,"y":0,},
  ],
  "parent": {
    "name": "4vs",
    "path": "folders/Rooms/Minigames/4vs.yy",
  },
  "parentRoom": null,
  "physicsSettings": {
    "inheritPhysicsSettings": false,
    "PhysicsWorld": false,
    "PhysicsWorldGravityX": 0.0,
    "PhysicsWorldGravityY": 10.0,
    "PhysicsWorldPixToMetres": 0.1,
  },
  "roomSettings": {
    "Height": 608,
    "inheritRoomSettings": false,
    "persistent": false,
    "Width": 2400,
  },
  "sequenceId": null,
  "views": [
    {"hborder":32,"hport":608,"hspeed":-1,"hview":608,"inherit":false,"objectId":null,"vborder":32,"visible":true,"vspeed":-1,"wport":800,"wview":800,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":608,"hspeed":-1,"hview":608,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":800,"wview":800,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":608,"hspeed":-1,"hview":608,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":800,"wview":800,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":608,"hspeed":-1,"hview":608,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":800,"wview":800,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":768,"hspeed":-1,"hview":768,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":1366,"wview":1366,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":768,"hspeed":-1,"hview":768,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":1366,"wview":1366,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":768,"hspeed":-1,"hview":768,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":1366,"wview":1366,"xport":0,"xview":0,"yport":0,"yview":0,},
    {"hborder":32,"hport":768,"hspeed":-1,"hview":768,"inherit":false,"objectId":null,"vborder":32,"visible":false,"vspeed":-1,"wport":1366,"wview":1366,"xport":0,"xview":0,"yport":0,"yview":0,},
  ],
  "viewSettings": {
    "clearDisplayBuffer": true,
    "clearViewBackground": false,
    "enableViews": true,
    "inheritViewSettings": false,
  },
  "volume": 1.0,
}