event_inherited();
aiming = true;
powering = false;
aim_angle = 45;
aim_power = 0;
powering_dir = 1;
max_power_velocity = 800;
on_block = false;
shot = false;
hole = false;
sound_count = 0;
phy_speed_previous = 0;