draw_set_alpha(animation_alpha);
language_set_font(fntDialogue);
var positive = (sign(amount) == 1);
draw_set_color((positive) ? c_blue : c_red);
draw_set_halign(fa_center);
focus_player = focus_player_by_id(network_id);
draw_sprite_ext(sprCoin, 0, focus_player.x - 12, focus_player.y - 40, 1, 1, 0, c_white, animation_alpha);
draw_set_halign(fa_left);
draw_text_outline(focus_player.x + 10, focus_player.y - 50, ((positive) ? "+" : "-") + string(abs(amount)), c_black);
draw_set_alpha(1);